name: Meteor.js Package

on:
  push:
    branches:
      - master

jobs:

  publish-atmosphere:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: meteorengineer/setup-meteor@v1.0.3
      - run: echo $METEOR_TOKEN > token.json && ll && meteor login
        env:
          METEOR_TOKEN: ${{secrets.METEOR_TOKEN}}
          METEOR_SESSION_FILE: token.json
      - run: meteor publish --update
          
